/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:d02c97fd-c1db-4e20-8d60-675565db785d",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_9AFzLHDKg",
    "aws_user_pools_web_client_id": "4aqftagjglkmgqf0pg92e4686r",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://s2gy3jxkqfhehmewutajksjcam.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
